// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountVisitors(ctx context.Context) (int64, error)
	CreateVisitor(ctx context.Context, data []byte) (VisitorVisitor, error)
	DeleteVisitor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetVisitor(ctx context.Context, id pgtype.UUID) (VisitorVisitor, error)
	ListVisitors(ctx context.Context, arg ListVisitorsParams) ([]VisitorVisitor, error)
	UpdateVisitor(ctx context.Context, arg UpdateVisitorParams) (VisitorVisitor, error)
}

var _ Querier = (*Queries)(nil)
