// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVisitor(ctx context.Context, data []byte) (VisitorVisitor, error)
	GetVisitor(ctx context.Context, id pgtype.UUID) (VisitorVisitor, error)
	ListVisitors(ctx context.Context) ([]VisitorVisitor, error)
}

var _ Querier = (*Queries)(nil)
