// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visitor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitor.visitors ("data")
VALUES ($1)
RETURNING id, data, created_at
`

func (q *Queries) CreateVisitor(ctx context.Context, data []byte) (VisitorVisitor, error) {
	row := q.db.QueryRow(ctx, createVisitor, data)
	var i VisitorVisitor
	err := row.Scan(&i.ID, &i.Data, &i.CreatedAt)
	return i, err
}

const getVisitor = `-- name: GetVisitor :one
SELECT id, data, created_at
FROM visitor.visitors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVisitor(ctx context.Context, id pgtype.UUID) (VisitorVisitor, error) {
	row := q.db.QueryRow(ctx, getVisitor, id)
	var i VisitorVisitor
	err := row.Scan(&i.ID, &i.Data, &i.CreatedAt)
	return i, err
}
